// Generated by https://quicktype.io

export class WeatherForecase {
    headline?:       Headline;
    dailyForecasts?: DailyForecast[];
}

export interface DailyForecast {
    date:        string;
    epochDate:   number;
    temperature: Temperature;
    day:         Day;
    night:       Day;
    sources:     string[];
    mobileLink:  string;
    link:        string;
}

export interface Day {
    icon:                    number;
    iconPhrase:              string;
    hasPrecipitation:        boolean;
    precipitationType?:      string;
    precipitationIntensity?: string;
}

export interface Temperature {
    minimum: Imum;
    maximum: Imum;
}

export interface Imum {
    value:    number;
    unit:     Unit;
    unitType: number;
}

export enum Unit {
    F = "F",
}

export interface Headline {
    effectiveDate:      string;
    effectiveEpochDate: number;
    severity:           number;
    text:               string;
    category:           string;
    endDate:            string;
    endEpochDate:       number;
    mobileLink:         string;
    link:               string;
}
